FROM python:3.11.2-alpine3.16

RUN mkdir -p /app

WORKDIR /app

ENV PYTHONUNBUFFERED = 1 

RUN apk update \
	&& apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev \
	&& pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt 

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]