# Generated by Django 4.1.7 on 2023-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_comment_video_remove_task_project_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='correp@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
