# Generated by Django 4.1.7 on 2023-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.TextField(default='url_no_dado', verbose_name=2000),
            preserve_default=False,
        ),
    ]
