# Generated by Django 4.1.7 on 2023-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='creator',
            field=models.CharField(max_length=100),
        ),
    ]
