# Generated by Django 3.2.18 on 2023-04-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='creator',
            field=models.TextField(default='', max_length=200),
        ),
    ]
