# Generated by Django 3.2.18 on 2023-04-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230402_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='video',
            name='src',
            field=models.TextField(default='hola', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
